import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:dio/dio.dart';
import '../../../data/models/auth_models.dart';
import '../../../data/models/user_model.dart';
import '../base/base_providers.dart';

part 'auth_provider.g.dart';

// ── Authentication Status Enum ─────────────────────────────────────────────────

/// Represents every possible authentication state the app can be in.
///
/// This drives the root-level routing in `MyApp._getHome()`.  The transitions
/// between statuses are managed exclusively by [AuthNotifier].
///
/// ### Status transition diagram
/// ```
/// (app start)
///      │
///      ▼
///   loading  ◄── app checking stored token
///      │
///      ├── token found + valid user ──► authenticated
///      │                                     │
///      │                                     ├── (new user) ──► onboarding
///      │                                     │                      │
///      │                                     └── (existing) ─────────┘
///      │
///      ├── no token ──► unauthenticated
///      │
///      └── (continueAsGuest) ──► guest
/// ```
///
/// `isSubmitting` is separate from this enum — it controls the login button's
/// inline spinner without triggering a full navigation change.
enum AuthStatus {
  /// The app has a logged-in user with a valid JWT.
  authenticated,

  /// No token exists and the user has not chosen to browse as a guest.
  unauthenticated,

  /// The user is browsing without an account.  They can view services but
  /// cannot book, chat, or access their profile.
  guest,

  /// [AuthNotifier._init] is checking the stored token on app startup.
  /// The splash screen is shown during this phase.
  loading,

  /// The user just registered but has not yet completed the onboarding flow.
  /// First-time users see the onboarding carousel before the main app.
  onboarding,
}

// ── Auth State ─────────────────────────────────────────────────────────────────

/// Immutable state object held by [AuthNotifier].
///
/// All fields are intentionally nullable (except [status]) so that the state
/// always has a valid default — Riverpod requires that providers have an
/// initial synchronous state before any async work completes.
///
/// ### Why not use Freezed for this?
/// [AuthState] is hand-written (not generated by Freezed) because:
/// 1. The `copyWith` needs special logic (e.g. clearing [errorMessage] when
///    [isSubmitting] becomes true).
/// 2. It avoids a code-generation step for a small, stable class.
class AuthState {
  /// The current authentication lifecycle phase.
  final AuthStatus status;

  /// The authenticated user's profile, or `null` when not logged in.
  final User? user;

  /// A user-facing error string set after a failed login/register attempt.
  /// Cleared (set to `null`) at the start of each new attempt.
  final String? errorMessage;

  /// `true` only while a login/register network call is in flight.
  ///
  /// Deliberately separate from [AuthStatus.loading] so that:
  /// - The root navigator does NOT switch screens while a login request is
  ///   pending (which would cause a jarring full-screen flash).
  /// - The login button can show a circular progress indicator inline.
  final bool isSubmitting;

  /// When set, the auth UI is locked until this [DateTime] passes.
  ///
  /// Set after receiving a 429 (Too Many Requests) response.
  /// The remaining time is shown to the user as a countdown.
  final DateTime? lockoutUntil;

  AuthState({
    this.status = AuthStatus.loading,
    this.user,
    this.errorMessage,
    this.isSubmitting = false,
    this.lockoutUntil,
  });

  /// Returns a new [AuthState] with the specified fields replaced.
  ///
  /// Note: [errorMessage] is NOT carried forward by default — it must be
  /// explicitly passed to persist it.  This prevents stale errors from
  /// lingering across unrelated state changes.
  AuthState copyWith({
    AuthStatus? status,
    User? user,
    String? errorMessage,
    bool? isSubmitting,
    DateTime? lockoutUntil,
  }) {
    return AuthState(
      status: status ?? this.status,
      user: user ?? this.user,
      errorMessage: errorMessage,  // intentionally NOT `errorMessage ?? this.errorMessage`
      isSubmitting: isSubmitting ?? this.isSubmitting,
      lockoutUntil: lockoutUntil ?? this.lockoutUntil,
    );
  }
}

// ── Auth Notifier ──────────────────────────────────────────────────────────────

/// The central Riverpod [Notifier] that manages the user's authentication
/// lifecycle for the entire application.
///
/// ## Architecture
/// [AuthNotifier] follows the **StateNotifier** pattern as implemented by
/// `riverpod_annotation`.  The `@riverpod` annotation generates
/// `authNotifierProvider` (in `auth_provider.g.dart`) for use in widgets:
/// ```dart
/// final authState = ref.watch(authNotifierProvider);
/// ```
///
/// ## Responsibilities
/// | Method                  | Purpose                                         |
/// |-------------------------|-------------------------------------------------|
/// | [_init]                 | Restore session from stored JWT on startup      |
/// | [login]                 | Authenticate with email/password                |
/// | [register]              | Create a new traveller/guide account            |
/// | [registerAsCompany]     | Two-step: register account + create company     |
/// | [continueAsGuest]       | Skip login, browse in guest mode                |
/// | [completeOnboarding]    | Mark onboarding as done, transition to app      |
/// | [updateLocalUser]       | Update cached user without a network call       |
/// | [logout]                | Clear token, return to unauthenticated state    |
///
/// ## Supabase shadow profile
/// After every successful authentication, [_transitionToUser] attempts to
/// fetch the user's avatar URL from a Supabase Storage bucket.  This is
/// completely optional — if Supabase is unavailable, the backend avatar
/// (or no avatar) is used instead.
@riverpod
class AuthNotifier extends _$AuthNotifier {
  @override
  AuthState build() {
    // The provider's initial synchronous state — must be returned immediately.
    // The real initialisation (token check) runs asynchronously in [_init].
    _init();
    return AuthState(); // status = AuthStatus.loading by default
  }

  // ── Initialisation ─────────────────────────────────────────────────────────

  /// Restores the user's session from the stored JWT on app startup.
  ///
  /// ### Flow
  /// 1. Read the JWT from [TokenStorage].
  /// 2. If no token → transition to [AuthStatus.unauthenticated].
  /// 3. If token exists → call `GET /api/auth/me` to validate it.
  /// 4. If valid → call [_transitionToUser] to set the user and role.
  /// 5. If invalid (e.g. expired) → transition to [AuthStatus.unauthenticated].
  ///
  /// During this entire process, the state remains [AuthStatus.loading] so
  /// the splash screen is shown.
  Future<void> _init() async {
    final storage = ref.read(tokenStorageProvider);
    final token = await storage.getToken();

    if (token == null) {
      state = state.copyWith(status: AuthStatus.unauthenticated);
      return;
    }

    try {
      final user = await ref.read(authRepositoryProvider).getMe();
      if (user != null) {
        await _transitionToUser(user);
      } else {
        state = state.copyWith(status: AuthStatus.unauthenticated);
      }
    } catch (e) {
      // Any error (network, expired token, etc.) defaults to unauthenticated.
      state = state.copyWith(status: AuthStatus.unauthenticated);
    }
  }

  // ── Login ──────────────────────────────────────────────────────────────────

  /// Logs in the user with [email] and [password].
  ///
  /// Uses [isSubmitting] instead of [AuthStatus.loading] to keep the login
  /// button's spinner local — the root navigator does not switch screens
  /// while the request is in flight.
  ///
  /// Existing users bypass onboarding since they have already completed it
  /// (this is enforced by passing `isNewUser: false` to [_transitionToUser]).
  Future<void> login(String email, String password) async {
    if (_isLockedOut()) return;

    state = state.copyWith(isSubmitting: true, errorMessage: null);
    try {
      final response = await ref
          .read(authRepositoryProvider)
          .login(LoginRequest(email: email, password: password));
      final user = await ref.read(authRepositoryProvider).getMe();
      if (user != null || response.user != null) {
        // Existing users skip onboarding — they already have an account.
        await _transitionToUser(user ?? response.user!, isNewUser: false);
      }
    } catch (e) {
      _handleAuthError(e);
    }
  }

  // ── Registration ───────────────────────────────────────────────────────────

  /// Registers a new user account and logs them in.
  ///
  /// New users are sent to the onboarding screen (see [AuthStatus.onboarding]).
  ///
  /// [role] defaults to `'User'` (regular traveller).  Pass `'TourGuide'`
  /// for guide registration if that flow is ever added.
  Future<void> register(
    String name,
    String email,
    String password, {
    String role = 'User',
  }) async {
    if (_isLockedOut()) return;

    state = state.copyWith(isSubmitting: true, errorMessage: null);
    try {
      final response = await ref
          .read(authRepositoryProvider)
          .register(
            RegisterRequest(
              name: name,
              email: email,
              password: password,
              role: role,
            ),
          );
      final user = await ref.read(authRepositoryProvider).getMe();
      if (user != null || response.user != null) {
        // Brand-new users go through onboarding.
        await _transitionToUser(user ?? response.user!, isNewUser: true);
      }
    } catch (e) {
      _handleAuthError(e);
    }
  }

  // ── Company Registration ────────────────────────────────────────────────────

  /// Registers a new **company manager** account and creates their company profile.
  ///
  /// This is a **two-step atomic flow** from the user's perspective:
  ///
  /// ### Step 1 — Register the user account
  /// Creates a user with `role: 'Manager'` via `POST /api/auth/register`.
  /// The JWT is saved to [TokenStorage] after this step.
  ///
  /// ### Step 2 — Create the company profile
  /// Uses the token obtained in Step 1 to call `POST /api/companies`.
  /// The company is created with `status: 'pending'` and requires admin
  /// approval before it becomes active.
  ///
  /// If Step 1 succeeds but Step 2 fails, the user account exists but has
  /// no company — [_handleAuthError] is called and the user must retry.
  Future<void> registerAsCompany(
    String name,
    String email,
    String password,
    String companyName,
    String companyDescription,
    String companyCategory,
    String? address,
    String? phone,
  ) async {
    if (_isLockedOut()) return;

    state = state.copyWith(isSubmitting: true, errorMessage: null);
    try {
      // Step 1: Register the user account with 'Manager' role
      final response = await ref
          .read(authRepositoryProvider)
          .register(
            RegisterRequest(
              name: name,
              email: email,
              password: password,
              role: 'Manager',
            ),
          );
      final user = await ref.read(authRepositoryProvider).getMe();

      if (user == null && response.user == null) {
        state = state.copyWith(
          isSubmitting: false,
          errorMessage: 'Registration failed.',
        );
        return;
      }

      // Step 2: Create the company profile (token is now stored from registration)
      // NOTE: This call uses the token just obtained, so it runs as the new manager.
      await ref.read(companyRepositoryProvider).createCompany({
        'name': companyName,
        'description': companyDescription,
        'category': companyCategory,
        if (address != null && address.isNotEmpty) 'address': address,
        if (phone != null && phone.isNotEmpty) 'phone': phone,
      });

      // Transition to the app — company is pending admin approval
      await _transitionToUser(user ?? response.user!, isNewUser: true);
    } catch (e) {
      _handleAuthError(e);
    }
  }

  // ── Guest Access ──────────────────────────────────────────────────────────

  /// Allows the user to browse the app without creating an account.
  ///
  /// Guests can view services and articles but cannot make bookings,
  /// send messages, or access their profile.
  void continueAsGuest() {
    state = state.copyWith(status: AuthStatus.guest);
  }

  // ── Onboarding ─────────────────────────────────────────────────────────────

  /// Marks the current user's onboarding as complete and transitions to the app.
  ///
  /// Persists the completion flag to [TokenStorage] so that future logins
  /// skip onboarding immediately.
  Future<void> completeOnboarding() async {
    if (state.user != null) {
      final storage = ref.read(tokenStorageProvider);
      await storage.saveOnboardingStatus(state.user!.id, true);
      state = state.copyWith(status: AuthStatus.authenticated);
    }
  }

  // ── Local Updates ─────────────────────────────────────────────────────────

  /// Replaces the cached [User] without making a network request.
  ///
  /// Used after profile updates (avatar, name) to refresh the UI immediately
  /// without requiring a full re-authentication.
  void updateLocalUser(User user) {
    state = state.copyWith(user: user);
  }

  // ── Logout ────────────────────────────────────────────────────────────────

  /// Logs out the current user.
  ///
  /// Deletes the JWT from [TokenStorage] and resets the state.  The root
  /// navigator in `MyApp._getHome` will detect [AuthStatus.unauthenticated]
  /// and show the login screen.
  Future<void> logout() async {
    await ref.read(authRepositoryProvider).logout();
    state = state.copyWith(status: AuthStatus.unauthenticated, user: null);
  }

  // ── Private Helpers ────────────────────────────────────────────────────────

  /// Returns `true` if the user is currently locked out from auth actions.
  ///
  /// Updates [errorMessage] with the remaining wait time if locked out.
  bool _isLockedOut() {
    if (state.lockoutUntil != null &&
        state.lockoutUntil!.isAfter(DateTime.now())) {
      final wait = state.lockoutUntil!.difference(DateTime.now()).inMinutes;
      state = state.copyWith(
        errorMessage: 'Too many attempts. Locked out for ${wait + 1} minutes.',
      );
      return true;
    }
    return false;
  }

  /// Handles errors from login/register calls.
  ///
  /// Special case: HTTP 429 (or an error message containing "Too many attempts")
  /// locks the UI for 15 minutes to mirror the server-side lockout window.
  void _handleAuthError(dynamic e) {
    if (e is DioException &&
        (e.response?.statusCode == 429 ||
            e.error.toString().contains('Too many attempts'))) {
      state = state.copyWith(
        isSubmitting: false,
        errorMessage: e.error.toString().contains('Too many attempts')
            ? e.error.toString()
            : 'Too many attempts. Please try again in 15 minutes.',
        lockoutUntil: DateTime.now().add(const Duration(minutes: 15)),
      );
    } else {
      state = state.copyWith(isSubmitting: false, errorMessage: e.toString());
    }
  }

  /// Determines the correct post-authentication state for [user] and applies it.
  ///
  /// ### Onboarding logic
  /// - `isNewUser: true` → check [TokenStorage] for the onboarding flag.
  ///   If not found, go to [AuthStatus.onboarding].
  /// - `isNewUser: false` → always skip onboarding (existing users are assumed
  ///   to have completed it) AND persist the flag for future logins.
  ///
  /// ### Supabase avatar
  /// After determining the auth status, attempts to fetch an avatar URL from
  /// Supabase Storage.  Errors are silently swallowed — the app functions
  /// perfectly without Supabase if credentials are not configured.
  Future<void> _transitionToUser(User user, {bool isNewUser = false}) async {
    final storage = ref.read(tokenStorageProvider);
    // For existing users logging in, always treat them as onboarded so they
    // never see the onboarding screen again regardless of local storage.
    final hasOnboarded = isNewUser
        ? await storage.getOnboardingStatus(user.id)
        : true;
    // Persist so future logins are also instant.
    if (!isNewUser) {
      await storage.saveOnboardingStatus(user.id, true);
    }

    // ── Fetch Shadow Profile (avatar) from Supabase ──────────────────────
    // This is an optional enhancement — if it fails, the app continues normally.
    String? supabaseAvatar;
    try {
      supabaseAvatar =
          await ref.read(profileRepositoryProvider).getAvatarUrl(user.id);
    } catch (_) {
      // Ignore errors fetching shadow profile
    }

    state = state.copyWith(
      status: hasOnboarded
          ? AuthStatus.authenticated
          : AuthStatus.onboarding,
      user: user.copyWith(avatar: supabaseAvatar ?? user.avatar),
      isSubmitting: false,
    );
  }
}
