// ignore_for_file: invalid_annotation_target
import 'package:freezed_annotation/freezed_annotation.dart';
import 'user_model.dart';

part 'auth_models.freezed.dart';
part 'auth_models.g.dart';

/// Data transfer objects (DTOs) for the SeYaha authentication API.
///
/// ## Pattern: Freezed + JSON serialisation
/// All models use `package:freezed` which code-generates:
/// - `copyWith` — immutable state updates
/// - `==` and `hashCode` — value equality (not reference equality)
/// - `toString` — useful for debugging
///
/// Combined with `package:json_annotation`, the `.g.dart` part file provides
/// `fromJson` / `toJson` serialisation automatically.
///
/// ## Code generation
/// After changing any model, run:
/// ```bash
/// dart run build_runner build --delete-conflicting-outputs
/// ```
/// The `.freezed.dart` and `.g.dart` files are generated and should NOT be
/// edited manually.

/// The response envelope returned by `POST /api/auth/login` and
/// `POST /api/auth/register`.
///
/// ```json
/// {
///   "success": true,
///   "token": "eyJ...",
///   "data": { "_id": "...", "name": "...", "role": "User", ... }
/// }
/// ```
///
/// The JWT [token] is saved to [TokenStorage] immediately after a successful
/// response (see [AuthRepository.login]).  The [user] field uses the
/// `@JsonKey(name: 'data')` annotation because the backend wraps the user
/// object in a `"data"` key — not `"user"`.
@freezed
class AuthResponse with _$AuthResponse {
  const factory AuthResponse({
    /// `true` when the request succeeded.
    required bool success,

    /// The JWT to be stored and attached to subsequent API requests as a
    /// `Bearer` token in the `Authorization` header.
    required String token,

    /// The authenticated user's profile, nested under the `"data"` key in
    /// the JSON response.  May be `null` on register if the backend doesn't
    /// return the profile immediately.
    @JsonKey(name: 'data') User? user,
  }) = _AuthResponse;

  factory AuthResponse.fromJson(Map<String, dynamic> json) =>
      _$AuthResponseFromJson(json);
}

/// Request body for `POST /api/auth/login`.
///
/// ```json
/// { "email": "user@example.com", "password": "s3cr3t" }
/// ```
///
/// Sent via [AuthRepository.login] after being serialised to JSON via
/// `toJson()` (generated by `json_annotation`).
@freezed
class LoginRequest with _$LoginRequest {
  const factory LoginRequest({
    /// The user's registered email address.
    required String email,

    /// The user's password (plaintext — TLS encrypts it in transit).
    required String password,
  }) = _LoginRequest;

  factory LoginRequest.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestFromJson(json);
}

/// Request body for `POST /api/auth/register`.
///
/// ```json
/// {
///   "name": "Ahmed Ali",
///   "email": "ahmed@example.com",
///   "password": "s3cr3t",
///   "role": "User"
/// }
/// ```
///
/// The [role] field defaults to `'user'` for normal registration.  Company
/// registration passes `'Manager'` (see [AuthNotifier.registerAsCompany]).
@freezed
class RegisterRequest with _$RegisterRequest {
  const factory RegisterRequest({
    /// The user's display name.
    required String name,

    /// The user's email address — must be unique in the backend database.
    required String email,

    /// The user's plaintext password — hashed server-side with bcrypt.
    required String password,

    /// The role to assign.  Defaults to `'user'` (regular traveller).
    /// Pass `'Manager'` for company account creation.
    @Default('user') String role,
  }) = _RegisterRequest;

  factory RegisterRequest.fromJson(Map<String, dynamic> json) =>
      _$RegisterRequestFromJson(json);
}
